version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/deploy

hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
  ApplicationStart:
    - location: scripts/start_container.sh
  ValidateService:
    - location: scripts/validate.sh
